# Generated by Django 2.2.1 on 2019-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190524_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', width_field=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_post',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
