# Generated by Django 2.2.1 on 2019-05-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190524_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
