# Generated by Django 2.2.1 on 2019-05-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190525_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
