# Generated by Django 2.2.1 on 2019-05-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190525_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Age',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
